version: 0.2

phases:
  install:
    commands:
    - make env
  build:
    commands:
    - make build
    - make package
  post_build:
    commands:
    - ls *

artifacts:
  type: zip
  files:
  - template.yml