version: 0.2

phases:
  install:
    commands:
    - env GOPATH=$PWD go env
    - env GOPATH=$PWD go version
  build:
    commands:
    - env GOPATH=$PWD go get ./src/canary/...
  post_build:
    commands:
    - ls *
